const marketTableData = [
    {
        "name":"BTCUSDT",
        "source":"Bitcoin",
        "profit":"$23,495",
        "status":true,
        "impression":"+23.4%"
    },
    {
        "name":"AXSUSDT",
        "source":"Axie Infinity",
        "profit":"$15.9",
        "status":false,
        "impression":"-7.8%"
    },
    {
        "name":"ETHUSDT",
        "source":"Ethereum",
        "profit":"$15,978",
        "status":false,
        "impression":"-0.3%"
    },
    {
        "name":"SOLUSDT",
        "source":"Solana",
        "profit":"$495",
        "status":true,
        "impression":"+11.1%"
    },
    {
        "name":"BNBUSDT",
        "source":"Binance",
        "profit":"$267",
        "status":true,
        "impression":"+6.7%"
    },
    {
        "name":"ADAUSDT",
        "source":"Cardano",
        "profit":"$0.49",
        "status":false,
        "impression":"-1.4%"
    }
]
export default marketTableData;